x<-read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE)
f<-as.factor(x[,1])
l<-levels(f)
x_s<-split(x,f)
p<-c(which(l=="1/2/2007"),which(l=="2/2/2007"))
X<-rbind(x_s[[p[1]]],x_s[[p[2]]])
X[,1]<-as.Date(X[,1],"%d/%m/%Y")
datetime<-paste(X$Date,X$Time)
v<-as.POSIXct(datetime)
png("plot2.png")
plot(X$Global_active_power ~ v,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()