x<-read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE)
f<-as.factor(x[,1])
l<-levels(f)
x_s<-split(x,f)
p<-c(which(l=="1/2/2007"),which(l=="2/2/2007"))
X<-rbind(x_s[[p[1]]],x_s[[p[2]]])
X[,1]<-as.Date(X[,1],"%d/%m/%Y")
datetime<-paste(X$Date,X$Time)
v<-as.POSIXct(datetime)
png("plot4.png")
par(mfrow = c(2,2))
plot(X$Global_active_power ~ v,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(X$Voltage ~ v, xlab="datetime",ylab="Voltage", type="l")
with(X,plot(X$Sub_metering_1 ~ v, type="l", xlab="", ylab="Energy sub metering"))
with(X,points(X$Sub_metering_2 ~ v, type="l",col="red"))
with(X,points(X$Sub_metering_3 ~ v, type="l",col="blue"))
legend("topright",lty=1,col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(X$Global_reactive_power ~ v, xlab="datetime",ylab="Global_reactive_power", type="l")
dev.off()